RManager/Models/Warehouse.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<double> FactualNumber { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Product Product { get; set; }
    }
}

RManager/Controllers/WarehouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RManager.Models;

namespace RManager.Controllers
{
    public class WarehouseController : Controller
    {
        private DataManager _DataManager;

        public WarehouseController(DataManager _DM)
        {
            _DataManager = _DM;
        }

        public ActionResult Warehouse()
        {
            var purchases = _DataManager.purchaseRepository.Purchases().Where(p => p.Warehouse.Product.IsExist);
            var ejections = _DataManager.ejectionRepository.Ejections().Where(e => e.Warehouse.Product.IsExist);
            var products = _DataManager.warehouseRepository.Warehouses().Where(p => p.Product.IsExist);
            
            SortedDictionary<Warehouse, double> productValues = new SortedDictionary<Warehouse, double>(new WarehouseComparer());
            foreach (Warehouse p in products) productValues.Add(p, !p.FactualNumber.HasValue ? 0 : p.FactualNumber.Value);
            foreach (Purchase p in purchases) if (p.Warehouse.Product.IsIngredient && p.Date > p.Warehouse.InspectionDate) productValues[p.Warehouse] += p.Volume;
            foreach (Ejection e in ejections) if (e.Warehouse.Product.IsIngredient && e.Date > e.Warehouse.InspectionDate) productValues[e.Warehouse] += e.Volume;

            SortedDictionary<Warehouse, double> productValues1 = new SortedDictionary<Warehouse, double>(new WarehouseComparer());
            SortedDictionary<Warehouse, double> productValue2 = new SortedDictionary<Warehouse, double>(new WarehouseComparer());
            foreach (var pv in productValues)
            {
                if (pv.Key.Product.IsIngredient) productValues1.Add(pv.Key, pv.Value);
                if (pv.Key.Product.IsMerchandise) productValue2.Add(pv.Key, pv.Value);
            }
            ViewData["ingredients"] = productValues1;
            ViewData["merchandises"] = productValue2;

            ViewData["prepacks"] = _DataManager.prepackRepository.Prepacks().Where(p => p.IsExist);

            ViewData["Companyes"] = _DataManager.companyRepository.Companyes();

            return View();
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult AddIngredient()
        {
            SortedList<int, string> sl = new SortedList<int, string>
            {
                { 0, "Граммы" },
                { 1, "Миллилитры" },
                { 2, "Штуки" }
            };
            ViewData["Measures"] = new SelectList(sl, "Key", "Value");

            sl = new SortedList<int, string>();
            foreach (Company c in _DataManager.companyRepository.Companyes())
            {
                sl.Add(c.Id, c.Name);
            }
            ViewData["Manufacturers"] = new SelectList(sl, "Key", "Value");

            sl = new SortedList<int, string>();
            foreach (Category c in _DataManager.categoryRepository.Categotyes())
            {
                sl.Add(c.Id, c.Name);
            }
            ViewData["Categoryes"] = new SelectList(sl, "Key", "Value");

            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult AddIngredient(string name, string property, string description, string vendorCode, int measure, int manufactorer,
            string lossDuringCleaning, string lossDuringFrying, string otherLosses,
            string cost, string volume, int category, string protains, string fats, string carbohydrates, string energyCalorie, string energyJoule)
        {
            if (string.IsNullOrWhiteSpace(name))
                ModelState.AddModelError("Name", "Введите название продукта");

            if (string.IsNullOrWhiteSpace(property))
                property = " ";

            if (string.IsNullOrWhiteSpace(description))
                property = " ";

            if (string.IsNullOrWhiteSpace(vendorCode))
                ModelState.AddModelError("VendorCode", "Введите артикул продукта");

            if (string.IsNullOrWhiteSpace(protains))
                protains = "0";
            else
            {
                try
                {
                    double co = Convert.ToDouble(protains);
                }
                catch
                {
                    ModelState.AddModelError("Protains", "Введите белки правильно");
                }
            }

            if (string.IsNullOrWhiteSpace(fats))
                fats = "0";
            else
            {
                try
                {
                    double co = Convert.ToDouble(fats);
                }
                catch
                {
                    ModelState.AddModelError("Fats", "Введите жиры правильно");
                }
            }

            if (string.IsNullOrWhiteSpace(carbohydrates))
                carbohydrates = "0";
            else
            {
                try
                {
                    double co = Convert.ToDouble(carbohydrates);
                }
                catch
                {
                    ModelState.AddModelError("Сarbohydrates", "Введите углеводы правильно");
                }
            }

            if (string.IsNullOrWhiteSpace(energyCalorie))
                energyCalorie = "0";
            else
            {
                try
                {
                    double co = Convert.ToDouble(energyCalorie);
                }
                catch
                {
                    ModelState.AddModelError("EnergyCalorie", "Введите ценность правильно");
                }
            }

            if (string.IsNullOrWhiteSpace(energyJoule))
                energyJoule = "0";
            else
            {
                try
                {
                    double co = Convert.ToDouble(energyJoule);
                }
                catch
                {
                    ModelState.AddModelError("EnergyJoule", "Введите ценность правильно");
                }
            }

            bool isIng = (!string.IsNullOrWhiteSpace(lossDuringCleaning) || !string.IsNullOrWhiteSpace(lossDuringFrying) || !string.IsNullOrWhiteSpace(otherLosses));
            bool isMer = (!string.IsNullOrWhiteSpace(cost) || !string.IsNullOrWhiteSpace(volume));
            if (!isMer) isIng = true;
            
            if (isIng)
            {
                if (string.IsNullOrWhiteSpace(lossDuringCleaning))
                    lossDuringCleaning = "0";
                else
                {
                    try
                    {
                        double co = Convert.ToDouble(lossDuringCleaning);
                    }
                    catch
                    {
                        ModelState.AddModelError("LossDuringCleaning", "Введите потери правильно");
                    }
                }

                if (string.IsNullOrWhiteSpace(lossDuringFrying))
                    lossDuringFrying = "0";
                else
                {
                    try
                    {
                        double co = Convert.ToDouble(lossDuringFrying);
                    }
                    catch
                    {
                        ModelState.AddModelError("LossDuringFrying", "Введите потери правильно");
                    }
                }

                if (string.IsNullOrWhiteSpace(otherLosses))
                    otherLosses = "0";
                else
                {
                    try
                    {
                        double co = Convert.ToDouble(otherLosses);
                    }
                    catch
                    {
                        ModelState.AddModelError("OtherLosses", "Введите потери правильно");
                    }
                }
            }

            if (isMer)
            {
                try
                {
                    decimal co = Convert.ToDecimal(cost);
                    if (co <= 0)
                        ModelState.AddModelError("Cost", "Введите цену");
                }
                catch
                {
                    ModelState.AddModelError("Cost", "Введите цену правильно");
                }

                try
                {
                    double co = Convert.ToDouble(volume);
                    if (co <= 0)
                        ModelState.AddModelError("Volume", "Введите количество");
                }
                catch
                {
                    ModelState.AddModelError("Volume", "Введите количество правильно");
                }
            }

            if ((from g in _DataManager.productRepository.Products()
                 where (g.Name == name && g.Property == property && g.Manufacturer.Id == manufactorer)
                 select g).Count() != 0)
                ModelState.AddModelError("Dublicate", "Такой продукт уже есть в базе данных");

            if (ModelState.IsValid)
            {
                if (isIng && isMer)
                    _DataManager.productRepository.AddProduct(name, property, description, Convert.ToDecimal(cost), Convert.ToDouble(volume), true, true,
                        (byte)measure, vendorCode, Convert.ToDouble(lossDuringCleaning), Convert.ToDouble(lossDuringFrying), Convert.ToDouble(otherLosses),
                        Convert.ToDouble(protains), Convert.ToDouble(fats), Convert.ToDouble(carbohydrates), Convert.ToDouble(energyCalorie), Convert.ToDouble(energyJoule),
                        _DataManager.categoryRepository.GetCategory(category), _DataManager.companyRepository.GetCompany(manufactorer));

                if (isIng && !isMer)
                    _DataManager.productRepository.AddIngredient(name, property,
                        (byte)measure, vendorCode, Convert.ToDouble(lossDuringCleaning), Convert.ToDouble(lossDuringFrying), Convert.ToDouble(otherLosses),

RManager/Views/Warehouse/AddIngredient.cshtml
@using RManager.Models

@{
    ViewBag.Title = "AddIngredient";
}

@if ((Employee)Session["user"] != null && ((Employee)Session["user"]).Position.WorkWithMenu)
{
    @Html.Partial("tabs")
    <h3>@Html.ActionLink("Склад", "Warehouse", "Warehouse") >> Добавить ингредиент</h3>

    <div class="panel panel-default">
        @using (Html.BeginForm())
    {
        <p class="input-group">
            <span class="input-group-addon">Название*:</span>
            <input type="text" class="form-control" name="name" placeholder="Название"> @Html.ValidationMessage("Name")
        </p>
        <p class="input-group">
            <span class="input-group-addon">Особенность:</span>
            <input type="text" class="form-control" name="property" placeholder="Особенность"> @Html.ValidationMessage("Property")
        </p>
        <p class="input-group">
            <span class="input-group-addon">Описание:</span>
            <input type="text" class="form-control" name="description" placeholder="Описание"> @Html.ValidationMessage("Description")
        </p>
        <p class="input-group">
            <span class="input-group-addon">Артикул:</span>
            <input type="text" class="form-control" name="vendorCode" placeholder="Артикул"> @Html.ValidationMessage("VendorCode")
        </p>
        <p class="input-group">
            <span class="input-group-addon">Единица измерения:</span>
            @Html.DropDownList("measure", (IEnumerable<SelectListItem>)ViewData["Measures"], htmlAttributes: new { @class = "form-control" })
        </p>
        <p class="input-group">
            <span class="input-group-addon">Белки:</span>
            <input type="text" class="form-control" name="protains" placeholder="Белки"> @Html.ValidationMessage("Protains")
        </p>
        <p class="input-group">
            <span class="input-group-addon">Жиры:</span>
            <input type="text" class="form-control" name="fats" placeholder="Жиры"> @Html.ValidationMessage("Fats")
        </p>
        <p class="input-group">
            <span class="input-group-addon">Углеводы:</span>
            <input type="text" class="form-control" name="carbohydrates" placeholder="Углеводы"> @Html.ValidationMessage("Carbohydrates")
        </p>
        <p class="input-group">
            <span class="input-group-addon">Энерг. ценность в ккал:</span>
            <input type="text" class="form-control" name="energyCalorie" placeholder="ккал"> @Html.ValidationMessage("EnergyCalorie")
        </p>
        <p class="input-group">
            <span class="input-group-addon">Энерг. ценность в ДЖ:</span>
            <input type="text" class="form-control" name="energyJoule" placeholder="ДЖ"> @Html.ValidationMessage("EnergyJoule")
        </p>
        <p class="input-group">
            <span class="input-group-addon">Производитель:</span>
            @Html.DropDownList("manufactorer", (IEnumerable<SelectListItem>)ViewData["Manufacturers"], htmlAttributes: new { @class = "form-control" })
        </p>
        <div class="panel panel-default">
            <h4>Поля для ингредиента</h4>
            <p class="input-group">
                <span class="input-group-addon">Потери при чистке%:</span>
                <input type="text" class="form-control" name="lossDuringCleaning" placeholder="Потери при чистке"> @Html.ValidationMessage("LossDuringCleaning")
            </p>
            <p class="input-group">
                <span class="input-group-addon">Потери при жарке%:</span>
                <input type="text" class="form-control" name="lossDuringFrying" placeholder="Потери при жарке"> @Html.ValidationMessage("LossDuringFrying")
            </p>
            <p class="input-group">
                <span class="input-group-addon">Другие потери%:</span>
                <input type="text" class="form-control" name="otherLosses" placeholder="Другие потери"> @Html.ValidationMessage("OtherLosses")
            </p>
        </div>
        <div class="panel panel-default">
            <h4>Поля для товара</h4>
            <p class="input-group">
                <span class="input-group-addon">Цена:</span>
                <input type="text" class="form-control" name="cost" placeholder="Цена"> @Html.ValidationMessage("Cost")
            </p>
            <p class="input-group">
                <span class="input-group-addon">Количество:</span>
                <input type="text" class="form-control" name="volume" placeholder="Количество"> @Html.ValidationMessage("Volume")
            </p>
            <p class="input-group">
                <span class="input-group-addon" id="ingridient">Категория:</span>
                @Html.DropDownList("category", (IEnumerable<SelectListItem>)ViewData["Categoryes"], htmlAttributes: new { @class = "form-control" })
            </p>
        </div>
        <p><input class="btn btn-default" type="submit" value="OK"></p>
        <p>@Html.ValidationMessage("Dublicate")</p>
}
    </div>
}

RManager/Views/Warehouse/Warehouse.cshtml
@using RManager.Models

@{
    ViewBag.Title = "Warehouse";
}

@if ((Employee)Session["user"] != null && ((Employee)Session["user"]).Position.WorkWithMenu)
{
    @Html.Partial("tabs")
<div class="panel panel-default">

    <h3>Работа со складом</h3>
    @{ if (((IEnumerable<Company>)ViewData["Companyes"]).Count() > 0)
        {
            @*<ul class="btn-group-vertical list-unstyled">
                <li>@Html.ActionLink("Добавить поставку", "AddPurchase", "Warehouse", htmlAttributes: new { @class = "btn btn-default" })</li>
                <li>@Html.ActionLink("Добавить списание продуктов", "AddEjection", "Warehouse", htmlAttributes: new { @class = "btn btn-default" })</li>
            </ul>*@
            <h4>Продукты на складе</h4>
            @Html.ActionLink("Добавить продукт", "AddIngredient", "Warehouse", htmlAttributes: new { @class = "btn btn-default" });
            @*@using (Html.BeginForm())
            {
                <p class="input-group">
                    <span class="input-group-addon" id="Firm">Поиск по названию(регистр важен):</span>
                    <input type="text" class="form-control" name="name" placeholder="Название">
                    <input class="btn btn-default" type="submit" value="Найти">@Html.ValidationMessage("Name")
                </p>
            }*@
            <div class="panel panel-default">
                <h5>Ингредиенты</h5>
                <table class="table table-bordered">
                    <tr>
                        <th>№</th>
                        <th>Артикул</th>
                        <th>Название        </th>
                        <th>Производитель   </th>
                        <th>Особенность     </th>
                        <th>На складе       </th>
                        <th>Изменить        </th>
                    </tr>

                    @{
                        //KeyValuePair<Product, double>[] products = ((KeyValuePair<Product, double>[])ViewData["ingredients"]);
                        IEnumerable<KeyValuePair<Warehouse, double>> products = ((IEnumerable<KeyValuePair<Warehouse, double>>)ViewData["ingredients"]);
                        for (int j = 0; j < products.Count(); j++)
                        {
                            <tr>
                                <td>@(j + 1)</td>
                                <th>@products.ElementAt(j).Key.Product.VendorCode</th>
                                <th>@products.ElementAt(j).Key.Product.Name</th>
                                <th>@products.ElementAt(j).Key.Product.Manufacturer.Name</th>
                                <th>@products.ElementAt(j).Key.Product.Property</th>
                                <th>@(products.ElementAt(j).Value.ToString() + " " + products.ElementAt(j).Key.Product.Measure.ToString())</th>
                                @*<th>@Html.ActionLink("Изменить", "EditIngredient", new { id = products.ElementAt(j).Key.Id })</th>*@
                            </tr>
                        }
                    }
                </table>

                <h5>Товары</h5>
                <table class="table table-bordered">
                    <tr>
                        <th>№</th>
                        <th>Артикул</th>
                        <th>Название        </th>
                        <th>Производитель   </th>
                        <th>Особенность     </th>
                        <th>На складе       </th>
                        <th>Изменить        </th>
                    </tr>

                    @{
                        products = ((IEnumerable<KeyValuePair<Warehouse, double>>)ViewData["merchandises"]);
                        for (int j = 0; j < products.Count(); j++)
                        {
                            <tr>
                                <td>@(j + 1)</td>
                                <th>@products.ElementAt(j).Key.Product.VendorCode</th>
                                <th>@products.ElementAt(j).Key.Product.Name</th>
                                <th>@products.ElementAt(j).Key.Product.Manufacturer.Name</th>
                                <th>@products.ElementAt(j).Key.Product.Property</th>
                                <th>@(products.ElementAt(j).Value.ToString() + " " + products.ElementAt(j).Key.Product.Measure.ToString())</th>
                                @*<th>@Html.ActionLink("Изменить", "EditIngredient", new { id = products.ElementAt(j).Key.Id })</th>*@
                            </tr>
                        }

                    }
                </table>

                <h4>Полуфабрикаты</h4>
                @*@Html.ActionLink("Добавить заготовку", "AddPrepack", "Warehouse", htmlAttributes: new { @class = "btn btn-default" })*@

                <table class="table table-bordered">
                    <tr>
                        <th>№</th>
                        <th>Артикул</th>
                        <th>Название        </th>
                        <th>Изменить        </th>
                    </tr>

                    @{
                        IEnumerable<Prepack> prepacks = ((IEnumerable<Prepack>)ViewData["prepacks"]);
                        for (int j = 0; j < prepacks.Count(); j++)
                        {
                            <tr>
                                <td>@(j + 1)</td>
                                <th>@prepacks.ElementAt(j).VendorCode</th>
                                <th>@prepacks.ElementAt(j).Name</th>
                                @*<th>@Html.ActionLink("Изменить", "EditIngredient", new { id = products.ElementAt(j).Key.Id })</th>*@
                            </tr>
                        }

                    }
                </table>
            </div>
        }
        else
        {
            <h4>Добавьте, хотя бы одну компанию поставщика</h4>
        }
    }
</div>
}
else
{
    <h4>Вы не выполнили вход, для работы необходимо выполнить вход.</h4>
}

RManager/Views/Warehouse/tabs.cshtml
@using RManager.Models

<ul class="nav nav-tabs">
    @if (((Employee)Session["user"]).Position.WorkWithOrders)
    {
        <li role="presentation">@Html.ActionLink("Заказы", "Orders", "Orders")</li>
    }
    @if (((Employee)Session["user"]).Position.WorkWithMenu)
    {
        <li role="presentation">@Html.ActionLink("Меню", "Menu", "Menu")</li>
    }
    @if (((Employee)Session["user"]).Position.WorkWithWarehouse)
    {
        <li role="presentation" class="active"><a href="#">Склад</a></li>
        <li role="presentation">@Html.ActionLink("Компании", "Companyes", "Companyes")</li>
    }
    @if (((Employee)Session["user"]).Position.WorkWithStuff)
    {
        <li role="presentation">@Html.ActionLink("Работники", "Workers", "Workers")</li>
    }
    @if (((Employee)Session["user"]).Position.WorkWithTables)
    {
        <li role="presentation">@Html.ActionLink("Столы", "Tables", "Tables")</li>
    }
    @if (((Employee)Session["user"]).Position.WorkWithReports)
    {
        <li role="presentation">@Html.ActionLink("Отчёт", "Reports", "Reports")</li>
    }
</ul>